import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StyleProviderCtx } from "@/contexts/StyleProviderContext";
import { NavBar } from "@/components/nav-bar";
import { Auth } from "@/contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyleProviderCtx>
          <Auth>
            <main className="min-h-screen">
              <NavBar />
              {children}
            </main>
          </Auth>
        </StyleProviderCtx>
      </body>
    </html>
  );
}
